DATASETS_PATH = "./Datasets/"
SCRIPTS_PATH = "./benchmarks/"
OUPUT_IMAGES_PATH = "./benchmarks/"
EXECUTION_OUTPUTS_PATH = "./benchmarks/"
EXECUTION_ERRORS_PATH = "./benchmarks/"
SHEETS = ['Benchmarks']
WORKBOOK_PATH = './Bulba Coding - ICE Correctness Rating Benchmarks 02_09_2023.xlsx'
ID_COLUMN = 'ID'
CODE_COLUMN = 'Model A Response'
FILENAME_COLUMN = 'CSV filename'